[theme]
base = "light"
primaryColor = "#2E86C1"
backgroundColor = "#FDFEFE"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#17202A"
font = "sans serif"

[server]
headless = true
enableCORS = false
